<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <IsAotCompatible>true</IsAotCompatible>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <!-- 强制输出到固定目录 -->
        <OutputPath>..\..\out</OutputPath>
        <!-- 禁止自动拼接 TargetFramework 和 RID -->
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

</Project>
